export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const PENDING_AUTH = 'PENDING_AUTH';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const CHANGE_VIEW = 'CHANGE_VIEW';

export const CREATE_HOUSEHOLD = 'CREATE_HOUSEHOLD';
export const PENDING_CREATE_HOUSEHOLD = 'PENDING_CREATE_HOUSEHOLD';
export const CREATE_HOUSEHOLD_ERROR = 'CREATE_HOUSEHOLD_ERROR';
export const GET_HOUSEHOLDS = 'GET_HOUSEHOLDS';
export const PENDING_GET_HOUSEHOLDS = 'PENDING_GET_HOUSEHOLDS';